---

- name: Flussonic Common Tasks
  hosts: all
  become: yes
  tags:
    - prod

  roles:
    - role: common

  vars_files:
    - settings.yml

- name: Production Deploy Tasks
  hosts: production
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  remote_user: "{{ ansible_ssh_user }}"
  tags: prod

  roles:
    # - role: prod
