---
- include: system.yml
- include: iptables.yml
- include: flussonic.yml

- name: copy root keys
  shell: "mkdir -p /home/{{ admin_user }}/.ssh && cp /root/.ssh/* /home/{{ admin_user }}/.ssh && chmod -R 0700 /home/{{ admin_user }}/.ssh && chown -R {{ admin_user }}:{{ admin_user }} /home/{{ admin_user }}/.ssh"
