---
- name: update network host
  hostname: name="{{ inventory_hostname }}"
  notify:
  - network restart

- name: set local hosts
  lineinfile:
    dest=/etc/hosts
    line="127.0.1.1 {{ inventory_hostname }} {{ ansible_hostname }}"
    regexp="^127\.0\.1\.1.*$"
    state=present
  when: not docker
  notify:
  - network restart

- name: set IP hosts
  lineinfile:
    dest=/etc/hosts
    line="{{ hostvars[inventory_hostname]['ansible_eth0']['ipv4']['address'] }} {{ inventory_hostname }} {{ ansible_hostname }}"
    regexp="^{{ hostvars[inventory_hostname]['ansible_eth0']['ipv4']['address'] }}.*$"
    state=present
  when: not docker
  notify:
  - network restart

- meta: flush_handlers
