---
- name: add multiverse
  apt_repository: repo='deb http://us.archive.ubuntu.com/ubuntu/ trusty multiverse' state=present update_cache=yes

- include: hosts.yml

- name: install deps using apt
  apt: name={{item}} state=present
  with_items:
    - language-pack-en
    - git
    - mc
    - htop
    - vim
    - wget
    - python-software-properties

- name: update locale
  locale_gen: name=en_US.UTF-8 state=present
  # command: update-locale LANG=en_US.UTF-8
  notify:
  - dpkg-reconfigure

- include: users.yml
- include: ssh.yml

- name: get iptables rules
  shell: iptables -L -n
  register: iptablesrules
  changed_when: false
  always_run: yes

- name: set file descriptor limits
  lineinfile: dest=/etc/security/limits.conf line="{{ item }}"
  with_items:
  - "root            soft    nofile 65536"
  - "root            hard    nofile 65536"

- name: open ports via iptables
  command: "/sbin/iptables -I INPUT 1 -p tcp --dport {{ item }} -m state --state NEW,ESTABLISHED -j ACCEPT"
  when: iptablesrules.stdout.find("dpt:{{ item }}") == -1 and iptablesrules.stdout.find("dpts:{{ item }}") == -1
  with_items: "{{ iptables.ports }}"
  notify:
  - iptables save
  - iptables restart

- meta: flush_handlers
