---
- name: update sshd config
  template:
    src: sshd_config.j2
    dest: "/etc/ssh/sshd_config"
    mode: 0600
    owner: root
    group: root
    validate: "/usr/sbin/sshd -T -f %s"
  notify: sshd restart
